# Generated by Django 6.0.5 on 2026-05-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='borrowed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='borrowed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', '대여 가능'), ('borrowed', '대여 중'), ('maintenance', '유지보수 중')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_day',
            field=models.IntegerField(default=0),
        ),
    ]
