# Generated by Django 6.0.5 on 2026-05-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_borrowed_at_product_borrowed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
        migrations.AddField(
            model_name='rental',
            name='borrower_name',
            field=models.CharField(default='알수없음', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('renting', '대여중'), ('returned', '반납완료')], default='renting', max_length=20),
        ),
    ]
